# Generated by Django 2.2.5 on 2019-10-06 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='volume_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimum allowed volume in m3', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
