# Generated by Django 2.2.5 on 2019-10-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='price_min',
            field=models.FloatField(blank=True, default=0, help_text='Minimum price in ISK'),
        ),
    ]
