# Generated by Django 2.2.5 on 2019-10-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_ownershiprecord'),
        ('eveonline', '0010_alliance_ticker'),
        ('freight', '0002_auto_20191004_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractsHandler',
            new_name='ContractHandler',
        ),
    ]
