# Generated by Django 2.2.5 on 2019-10-06 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0002_pricing_price_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='collateral_min',
            field=models.BigIntegerField(blank=True, default=None, help_text='Minimum required collateral in ISK', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days_to_complete',
            field=models.IntegerField(blank=True, default=None, help_text='Recommended days for contract completion', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days_to_expire',
            field=models.IntegerField(blank=True, default=None, help_text='Recommended days for contracts to expire', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_base',
            field=models.FloatField(blank=True, default=None, help_text='Base price in ISK', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_min',
            field=models.FloatField(blank=True, default=None, help_text='Minimum total price in ISK', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_per_collateral_percent',
            field=models.FloatField(blank=True, default=None, help_text='Add-on price in % of collaterial', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_per_volume',
            field=models.FloatField(blank=True, default=None, help_text='Add-on price per m3 volume in ISK', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
