# Generated by Django 2.2.5 on 2019-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_auto_20191005_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freight',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('setup_contract_handler', 'Can setup contract handler'), ('use_calculator', 'Can use the calculator'), ('view_contracts', 'Can view the contracts list'), ('add_location', 'Can add / update locations'), ('view_statistics', 'Can view freight statistics'))},
        ),
        migrations.AddField(
            model_name='contract',
            name='date_notified',
            field=models.DateTimeField(default=None, help_text='datetime of latest notification, None = none has been sent', null=True),
        ),
    ]
