# Generated by Django 2.2.5 on 2019-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_auto_20191006_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_notified',
            field=models.DateTimeField(default=None, help_text='datetime of latest notification, None = none has been sent', null=True),
        ),
    ]
