# Generated by Django 2.2.5 on 2019-10-06 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_auto_20191006_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='collateral_max',
            field=models.BigIntegerField(blank=True, default=None, help_text='Maximum allowed collateral in ISK', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days_to_complete',
            field=models.IntegerField(blank=True, default=None, help_text='Recommended days for contract completion', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days_to_expire',
            field=models.IntegerField(blank=True, default=None, help_text='Recommended days for contracts to expire', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='volume_max',
            field=models.FloatField(blank=True, default=None, help_text='Maximum allowed volume in m3', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
