# Generated by Django 2.2.5 on 2019-10-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0004_auto_20191005_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pricing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='freight.Pricing'),
        ),
    ]
