# Generated by Django 2.2.5 on 2019-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0004_auto_20191006_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthandler',
            name='last_error',
            field=models.IntegerField(choices=[(0, 'No error'), (1, 'Invalid token'), (2, 'Expired token'), (3, 'Insufficient permissions'), (4, 'No character set for fetching alliance contacts'), (5, 'ESI API is currently unavailable'), (99, 'Unknown error')], default=0),
        ),
    ]
