# Generated by Django 2.2.5 on 2019-10-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0004_contract_date_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracthandler',
            name='send_notifications',
        ),
    ]
