# Generated by Django 2.2.5 on 2019-10-03 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0016_ownershiprecord'),
        ('eveonline', '0010_alliance_ticker'),
        ('evesde', '0014_delete_evename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.EveSolarSystem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.EveType')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='evesde.EveItem')),
                ('structure', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jfservice.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='JfService',
            fields=[
                ('alliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eveonline.EveAllianceInfo')),
                ('price_per_volume', models.FloatField(default=None, null=True)),
                ('price_collateral_percent', models.FloatField(default=None, null=True)),
                ('collateral_max', models.BigIntegerField(default=None, null=True)),
                ('price_minimum', models.FloatField(default=None, null=True)),
                ('character', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.CharacterOwnership')),
            ],
            options={
                'permissions': (('access_jfservice', 'Can access the JF Service'),),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral', models.FloatField()),
                ('contract_id', models.IntegerField()),
                ('date_accepted', models.DateTimeField(default=None, null=True)),
                ('date_completed', models.DateTimeField(default=None, null=True)),
                ('date_expired', models.DateTimeField()),
                ('date_issued', models.DateTimeField()),
                ('days_to_complete', models.IntegerField()),
                ('for_corporation', models.BooleanField()),
                ('price', models.FloatField()),
                ('reward', models.FloatField()),
                ('status', models.CharField(max_length=32)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('volume', models.FloatField()),
                ('acceptor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_acceptor', to='eveonline.EveCharacter')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_end_location', to='jfservice.Location')),
                ('issue_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_issuer', to='eveonline.EveCorporationInfo')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_issuer', to='eveonline.EveCharacter')),
                ('jfservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfservice.JfService')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_start_location', to='jfservice.Location')),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='jfservice_c_status_67ae0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('jfservice', 'contract_id')},
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('outstanding', 'outstanding'), ('in_progress', 'in progress'), ('finished_issuer', 'finished issuer'), ('finished_contractor', 'finished contractor'), ('finished', 'finished'), ('canceled', 'canceled'), ('rejected', 'rejected'), ('failed', 'failed'), ('deleted', 'deleted'), ('reversed', 'reversed')], max_length=32),
        ),
        migrations.AddField(
            model_name='jfservice',
            name='last_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jfservice',
            name='version_hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='issue_corporation',
            new_name='issuer_corporation',
        ),
        migrations.RenameField(
            model_name='jfservice',
            old_name='price_minimum',
            new_name='price_base',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='collateral_max',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='price_base',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='price_collateral_percent',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='price_per_volume',
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('price_per_volume', models.FloatField(default=None, null=True)),
                ('price_collateral_percent', models.FloatField(default=None, null=True)),
                ('collateral_max', models.BigIntegerField(default=None, null=True)),
                ('price_base', models.FloatField(default=None, null=True)),
                ('volume_max', models.FloatField(default=None, null=True)),
                ('pricing_comment', models.TextField(default=None, null=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_end_location', to='jfservice.Location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_start_location', to='jfservice.Location')),
            ],
            options={
                'unique_together': {('start_location', 'end_location')},
            },
        ),
        migrations.RenameModel(
            old_name='JfService',
            new_name='ContractsHandler',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='jfservice',
            new_name='handler',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('handler', 'contract_id')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='item',
        ),
        migrations.RemoveField(
            model_name='location',
            name='structure',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='solar_system_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='type_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='category_id',
            field=models.IntegerField(choices=[(3, 'station'), (65, 'structure'), (0, '(unknown)')], default=0),
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
