# Generated by Django 2.2.5 on 2019-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0001_squashed_0004_remove_pricing_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('create_service', 'Can create / update a freight service'), ('use_calculator', 'Can use the calculator'), ('view_contracts', 'Can view the contracts list'), ('add_location', 'Can add / update locations'), ('view_statistics', 'Can view freight statistics')),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contractshandler',
            options={},
        ),
    ]
