# Generated by Django 2.2.5 on 2019-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0001_squashed_0006_auto_20191004_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='name',
            field=models.CharField(default='xyz', max_length=50),
            preserve_default=False,
        ),
    ]
