# Generated by Django 2.2.5 on 2019-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0002_auto_20191002_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='jfservice',
            name='last_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jfservice',
            name='version_hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
