# Generated by Django 2.2.5 on 2019-10-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0002_auto_20191004_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freightservice',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('create_service', 'Can create / update a freight service'), ('use_calculator', 'Can use the calculator'), ('view_contracts', 'Can view the contracts list'), ('add_location', 'Can add / update locations'), ('view_statistics', 'Can view freight statistics'))},
        ),
    ]
