# Generated by Django 2.2.5 on 2019-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0002_pricing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
