# Generated by Django 2.2.5 on 2019-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0002_auto_20191004_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='comment',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='price_collateral_percent',
            new_name='price_per_collateral_percent',
        ),
        migrations.AddField(
            model_name='pricing',
            name='collateral_min',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
