# Generated by Django 2.2.5 on 2019-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0003_auto_20191004_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='days_to_complete',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='days_to_expire',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
