# Generated by Django 2.2.5 on 2019-10-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0003_auto_20191002_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='issue_corporation',
            new_name='issuer_corporation',
        ),
    ]
