# Generated by Django 2.2.5 on 2019-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0004_auto_20191004_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='collateral_max',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='collateral_min',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days_to_complete',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='days_to_expire',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_base',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_per_collateral_percent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_per_volume',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='volume_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
