# Generated by Django 2.2.5 on 2019-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0004_auto_20191002_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='jfservice',
            name='pricing_comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jfservice',
            name='volume_max',
            field=models.FloatField(default=None, null=True),
        ),
    ]
