# Generated by Django 2.2.5 on 2019-10-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0005_auto_20191002_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jfservice',
            old_name='price_minimum',
            new_name='price_base',
        ),
    ]
