# Generated by Django 2.2.5 on 2019-10-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0006_auto_20191002_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jfservice',
            name='collateral_max',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='price_base',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='price_collateral_percent',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='price_per_volume',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='pricing_comment',
        ),
        migrations.RemoveField(
            model_name='jfservice',
            name='volume_max',
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('price_per_volume', models.FloatField(default=None, null=True)),
                ('price_collateral_percent', models.FloatField(default=None, null=True)),
                ('collateral_max', models.BigIntegerField(default=None, null=True)),
                ('price_base', models.FloatField(default=None, null=True)),
                ('volume_max', models.FloatField(default=None, null=True)),
                ('pricing_comment', models.TextField(default=None, null=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_end_location', to='jfservice.Location')),
                ('jfservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfservice.JfService')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_start_location', to='jfservice.Location')),
            ],
            options={
                'unique_together': {('jfservice', 'start_location', 'end_location')},
            },
        ),
    ]
