# Generated by Django 2.2.5 on 2019-10-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0007_auto_20191002_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('start_location', 'end_location')},
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='jfservice',
        ),
    ]
