# Generated by Django 2.2.5 on 2019-10-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_ownershiprecord'),
        ('eveonline', '0010_alliance_ticker'),
        ('jfservice', '0008_auto_20191002_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JfService',
            new_name='ContractsHandler',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='jfservice',
            new_name='handler',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('handler', 'contract_id')},
        ),
    ]
