# Generated by Django 2.2.5 on 2019-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0009_auto_20191002_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='item',
        ),
        migrations.RemoveField(
            model_name='location',
            name='structure',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='solar_system_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='type_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
