# Generated by Django 2.2.5 on 2019-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0010_auto_20191003_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.IntegerField(choices=[(3, 'station'), (65, 'structure')], default=3),
            preserve_default=False,
        ),
    ]
