# Generated by Django 2.2.5 on 2019-10-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0011_location_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
