# Generated by Django 2.2.5 on 2019-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0012_delete_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.IntegerField(choices=[(3, 'station'), (65, 'structure')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='solar_system_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
