# Generated by Django 2.2.5 on 2019-10-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfservice', '0014_auto_20191003_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='category',
            new_name='category_id',
        ),
    ]
